### PR TITLE
change

### PR DESCRIPTION
**Pull request by jeffuc**

### CODE REVIEW

**Comment by evmyclipz** [comment]
https://evmyclipz.github.io/sample1_blog/

**Comment by jm1021** [comment]
Not accepted

**Comment by evmyclipz** [comment]
What am I missing?

**Comment by evmyclipz** [comment]
I changed my fast pages blog, can you please verify?

**Comment by evmyclipz** [comment]
I have changed my fast page blog, can you please verify?

**Comment by evmyclipz** [comment]
What am I missing?

**Pull request closed without merging**
